name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace placeholders with secrets
        run: |
          sed -i 's#{{FIREBASE_API_KEY}}#${{ secrets.FIREBASE_API_KEY }}#g' index.html
          sed -i 's#{{FIREBASE_AUTH_DOMAIN}}#${{ secrets.FIREBASE_AUTH_DOMAIN }}#g' index.html
          sed -i 's#{{FIREBASE_DATABASE_URL}}#${{ secrets.FIREBASE_DATABASE_URL }}#g' index.html
          sed -i 's#{{FIREBASE_PROJECT_ID}}#${{ secrets.FIREBASE_PROJECT_ID }}#g' index.html
          sed -i 's#{{FIREBASE_STORAGE_BUCKET}}#${{ secrets.FIREBASE_STORAGE_BUCKET }}#g' index.html
          sed -i 's#{{FIREBASE_MESSAGING_SENDER_ID}}#${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}#g' index.html
          sed -i 's#{{FIREBASE_APP_ID}}#${{ secrets.FIREBASE_APP_ID }}#g' index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .  # Deploy the current directory (with updated index.html)
